python_version = "3.13"
docs_base_url = "https://docs.python.org/3.13"

order = [
  "hello-world",
  "values",
  "numbers",
  "booleans",
  "none",
  "variables",
  "constants",
  "truthiness",
  "equality-and-identity",
  "mutability",
  "strings",
  "string-formatting",
  "conditionals",
  "for-loops",
  "iterating-over-iterables",
  "iterators",
  "match-statements",
  "while-loops",
  "lists",
  "tuples",
  "unpacking",
  "dicts",
  "sets",
  "slices",
  "comprehensions",
  "sorting",
  "functions",
  "keyword-only-arguments",
  "args-and-kwargs",
  "multiple-return-values",
  "closures",
  "recursion",
  "lambdas",
  "generators",
  "generator-expressions",
  "itertools",
  "decorators",
  "classes",
  "dataclasses",
  "properties",
  "special-methods",
  "context-managers",
  "exceptions",
  "modules",
  "type-hints",
  "enums",
  "regular-expressions",
  "number-parsing",
  "custom-exceptions",
  "json",
  "datetime",
  "async-await",
]
