#!/usr/bin/env python3
"""Embed Markdown example sources in a Python module for Cloudflare Workers."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src" / "example_sources"
TARGET = ROOT / "src" / "example_sources_data.py"


def main() -> None:
    entries = {path.name: path.read_text() for path in sorted(SOURCE_DIR.glob("*.md"))}
    entries["manifest.toml"] = (SOURCE_DIR / "manifest.toml").read_text()
    TARGET.write_text(
        "# Generated by scripts/embed_example_sources.py. Do not edit by hand.\n"
        f"EXAMPLE_SOURCE_FILES = {entries!r}\n"
    )
    print(f"Embedded {len(entries)} example source file(s).")


if __name__ == "__main__":
    main()
