#!/usr/bin/env python3
"""Embed the TOML editorial registry for Cloudflare Python Workers.

Wrangler bundles Python modules and template files under ``src/`` but not the
``docs/`` directory. Keep the human-edited source in TOML, then generate this
small Python fallback so runtime imports have the same data in production.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "quality-registries.toml"
TARGET = ROOT / "src" / "editorial_registry_data.py"


def main() -> None:
    text = SOURCE.read_text()
    TARGET.write_text(
        "# Generated by scripts/embed_editorial_registry.py. Do not edit by hand.\n"
        f"REGISTRY_TOML = {text!r}\n"
    )
    print(f"Embedded editorial registry ({len(text.encode('utf-8'))} bytes).")


if __name__ == "__main__":
    main()
