#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import re

from _common import ROOT
from src.security import CONTENT_SECURITY_POLICY, STRICT_TRANSPORT_SECURITY

PUBLIC = ROOT / "public"
MANIFEST = ROOT / "src" / "asset_manifest.py"

ASSETS = {
    "SITE_CSS": "site.css",
    "SYNTAX_JS": "syntax-highlight.js",
    "EDITOR_JS": "editor.js",
    "RUNNER_JS": "runner.js",
    "SEARCH_JS": "search.js",
    "SEARCH_INDEX": "search-index.json",
}


def fingerprint(filename: str) -> str:
    source = PUBLIC / filename
    content = source.read_bytes()
    digest = hashlib.sha256(content).hexdigest()[:12]
    stem = source.stem
    suffix = source.suffix
    target_name = f"{stem}.{digest}{suffix}"

    for old in PUBLIC.glob(f"{stem}.*{suffix}"):
        if re.fullmatch(rf"{re.escape(stem)}\.[0-9a-f]{{12}}{re.escape(suffix)}", old.name):
            old.unlink()

    (PUBLIC / target_name).write_bytes(content)
    return f"/{target_name}"


def html_version(paths: dict[str, str]) -> str:
    digest = hashlib.sha256()
    for value in sorted(paths.values()):
        digest.update(value.encode("utf-8"))
    content_paths = [
        ROOT / "docs" / "quality-registries.toml",
        ROOT / "src" / "app.py",
        ROOT / "src" / "editorial_registry.py",
        ROOT / "src" / "editorial_registry_data.py",
        ROOT / "src" / "examples.py",
        ROOT / "src" / "example_loader.py",
        ROOT / "src" / "example_sources_data.py",
        ROOT / "src" / "main.py",
        ROOT / "src" / "marginalia.py",
        ROOT / "src" / "marginalia_grammar.py",
        ROOT / "src" / "security.py",
        ROOT / "src" / "example_sources" / "manifest.toml",
        *sorted((ROOT / "src" / "example_sources").glob("*.md")),
        *sorted((ROOT / "src" / "templates").glob("*.html")),
    ]
    for path in content_paths:
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()[:12]


def main() -> None:
    paths = {name: fingerprint(filename) for name, filename in ASSETS.items()}
    version = html_version(paths)
    MANIFEST.write_text(
        "# Generated by scripts/fingerprint_assets.py. Do not edit by hand.\n"
        f"ASSET_PATHS = {paths!r}\n"
        f"HTML_CACHE_VERSION = {version!r}\n"
    )
    (PUBLIC / "_headers").write_text(
        "/*\n"
        "  X-Content-Type-Options: nosniff\n"
        "  Referrer-Policy: strict-origin-when-cross-origin\n"
        "  X-Frame-Options: DENY\n"
        f"  Strict-Transport-Security: {STRICT_TRANSPORT_SECURITY}\n"
        f"  Content-Security-Policy: {CONTENT_SECURITY_POLICY}\n\n"
        "/site.*.css\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/syntax-highlight.*.js\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/editor.*.js\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/runner.*.js\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/search.*.js\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/search-index.*.json\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/favicon.svg\n"
        "  Cache-Control: public, max-age=31536000, immutable\n\n"
        "/og/*\n"
        "  Cache-Control: public, max-age=86400\n\n"
        "/prototyping/*\n"
        "  Cache-Control: no-cache, must-revalidate\n"
    )
    for name, path in paths.items():
        print(f"{name}={path}")


if __name__ == "__main__":
    main()
