# Generated by scripts/fingerprint_assets.py. Do not edit by hand.
ASSET_PATHS = {'SITE_CSS': '/site.215b3101140a.css', 'SYNTAX_JS': '/syntax-highlight.d6178fb3eef5.js', 'EDITOR_JS': '/editor.32983031ee9a.js', 'RUNNER_JS': '/runner.a5b99ceb274f.js', 'SEARCH_JS': '/search.ab0effeac6ce.js', 'SEARCH_INDEX': '/search-index.332712b2e502.json'}
HTML_CACHE_VERSION = '1895cf9b1c6a'
